### ISSUE TITLE
Make settings an actual environment key

### ISSUE THREAD

**Issue by twodayslate** [twodayslate/claw#15]
https://swiftwithmajid.com/2020/12/09/styling-custom-swiftui-views-using-environment/

**Comment by twodayslate** [comment]
This should also be applied to openURL and observableSheet

**Comment by WhollySoftware** [comment]
Hello sir 

I checked and try to make environment key of setting but there is problem is when we try to make it then all setting not apply in complete app because environment key used is pass data to all sub screen or view. but in your project we need to update object from sub view to main view.
