### ISSUE TITLE
App does not display any posts from threads

### ISSUE THREAD

**Issue by codingnooob** [twodayslate/claw#56]
All of the threads in the app appear like this:

![image](https://github.com/twodayslate/claw/assets/66186626/e76b4593-c2a4-4380-bccc-08c74ce13ef8)
![image](https://github.com/twodayslate/claw/assets/66186626/f1411d63-3e24-4ef9-95b5-24505a83e6f1)
![image](https://github.com/twodayslate/claw/assets/66186626/f9cbd78b-37ad-47b6-a687-e4375b8b9710)

I'm using an iPhone SE 2 on iOS 17.3.1 and app version 1.5.1

**Comment by twodayslate** [comment]
Looks like this broke it 
https://github.com/lobsters/lobsters/commit/0747697ddb7393d3f60fc58b0c986fda48fbe8a3

**Comment by twodayslate** [comment]
This was submitted yesterday for review. I have requested an expedited review for this

**Comment by twodayslate** [comment]
This is now in the App Store
